#! /usr/bin/env node

const {execRegtest} = require('./exec-regtest')

const runRegtest = async () => {
    await execRegtest()
    console.log('bitcoind start.')
}

runRegtest().catch(err => console.error(err))
